import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {validateGraph,toFlow,aggregate,parseGraph,canResolve} from './graph-model.mjs';
const work=(id,deps=[])=>({id,kind:{type:'work',agent:'worker',prompt:'task'},depends_on:deps.map(node=>({node}))});
const graph=(nodes)=>({version:1,name:'test',max_parallel:4,nodes});
test('linear topological layers',()=>assert.deepEqual(validateGraph(graph([work('a'),work('b',['a'])])).layers,[['a'],['b']]));
test('siblings share one layer',()=>assert.deepEqual(validateGraph(graph([work('a'),work('b')])).layers,[['a','b']]));
test('cycle rejected',()=>assert.throws(()=>validateGraph(graph([work('a',['b']),work('b',['a'])]))));
test('duplicate node rejected',()=>assert.throws(()=>validateGraph(graph([work('a'),work('a')]))));
test('unknown predecessor rejected',()=>assert.throws(()=>validateGraph(graph([work('a',['missing'])]))));
test('self dependency rejected',()=>assert.throws(()=>validateGraph(graph([work('a',['a'])]))));
test('boolean edge cannot come from work',()=>{const b=work('b',['a']);b.depends_on[0].on='true';assert.throws(()=>validateGraph(graph([work('a'),b])));});
test('branch needs source as dependency',()=>assert.throws(()=>validateGraph(graph([{id:'b',kind:{type:'branch',source:'a',pointer:'/ok',equals:true}},work('a')]))));
test('flow reflects uncertain instead of success',()=>{const f=toFlow(graph([work('a')]),{nodes:{a:{status:'uncertain'}}});assert.equal(f.nodes[0].data.status,'uncertain');});
test('partial is not completed',()=>assert.equal(aggregate({nodes:{a:{status:'completed'},b:{status:'partial'}}}),'partial'));
test('all skipped/completed means completed',()=>assert.equal(aggregate({nodes:{a:{status:'completed'},b:{status:'skipped'}}}),'completed'));
test('missing state is invalid',()=>assert.equal(aggregate({nodes:{}}),'invalid'));
test('unknown checkpoint state is rejected',()=>assert.throws(()=>toFlow(graph([work('a')]),{nodes:{a:{status:'magic'}}})));
test('human resolution needs matching revision',()=>{const c={revision:3,nodes:{a:{status:'waiting'}}};assert.equal(canResolve(c,'a',3),true);assert.equal(canResolve(c,'a',2),false);});
test('JSON parse validates definition',()=>assert.equal(parseGraph(JSON.stringify(graph([work('a')]))).nodes.length,1));
test('oversized JSON rejected',()=>assert.throws(()=>parseGraph(' '.repeat(2*1024*1024+1))));
test('prototype names do not read inherited checkpoint state',()=>assert.equal(toFlow(graph([work('constructor')])).nodes[0].data.status,'pending'));
test('unknown node kinds rejected',()=>assert.throws(()=>validateGraph(graph([{id:'a',kind:{type:'computer-root'}}]))));
test('page withholds host callbacks until graph status is armed',()=>{
  const page=readFileSync(new URL('../../pages/HarnessGraphPage.tsx',import.meta.url),'utf8');
  assert.match(page,/status\.data\?\.graph && projectId/);
  assert.match(page,/if \(!armed\) return \{\}/);
  const bench=readFileSync(new URL('./HarnessGraphWorkbench.tsx',import.meta.url),'utf8');
  assert.match(bench,/disabled=\{busy\|\|!onStart/);
  assert.match(bench,/disabled=\{busy\|\|!onResume/);
});
